# Generated by Django 4.0.1 on 2022-02-17 05:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messageapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workerapp', '0001_initial'),
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterToWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=500, message='Превышена максимально допустимая длина')], verbose_name='Текст письма')),
                ('response_status', models.CharField(choices=[(1, 'Отказ'), (2, 'Приглашение')], max_length=500, verbose_name='Статус ответа')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата ответа')),
            ],
        ),
        migrations.CreateModel(
            name='MessageOnResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата предложения')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageapp.message', verbose_name='Отклик')),
                ('resume', models.ManyToManyField(to='workerapp.Resume', verbose_name='Резюме')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.vacancy', verbose_name='Вакансия')),
            ],
        ),
    ]
