# Generated by Django 4.0.1 on 2022-02-17 05:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование организации')),
                ('category', models.IntegerField(choices=[(1, 'Автомобильный бизнес'), (2, 'Гостиницы, рестораны, общепит, кейтеринг'), (3, 'Государственные организации'), (4, 'Добывающая отрасль'), (5, 'ЖКХ'), (6, 'Строительство, недвижимость, эксплуатация, проектирование'), (7, 'Услуги для бизнеса'), (8, 'Финансовый сектор'), (9, 'Электроника, приборостроение, бытовая техника, компьютеры и оргтехника'), (10, 'Энергетика'), (11, 'Другое')], verbose_name='Отрасль')),
                ('itn', models.BigIntegerField(unique=True, verbose_name='ИНН')),
                ('company_details', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=1000, message='Превышена максимально допустимая длина')], verbose_name='Сведения о компании')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=2000, message='Превышена максимально допустимая длина')], verbose_name='Описание')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('conditions', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=2500, message='Превышена максимально допустимая длина')], verbose_name='Условия')),
                ('duties', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=2500, message='Превышена максимально допустимая длина')], verbose_name='Обязанности')),
                ('requirements', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=2500, message='Превышена максимально допустимая длина')], verbose_name='Требования')),
                ('salary', models.CharField(blank=True, max_length=64, null=True, verbose_name='Зарплата')),
                ('city', models.CharField(blank=True, max_length=64, null=True, verbose_name='Город')),
                ('published_date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('company_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.companycard', verbose_name='Организация')),
            ],
        ),
    ]
