# Generated by Django 4.0.1 on 2022-01-22 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Наименование организации')),
                ('category', models.IntegerField(choices=[(1, 'Автомобильный бизнес'), (2, 'Гостиницы, рестораны, общепит, кейтеринг'), (3, 'Государственные организации'), (4, 'Добывающая отрасль'), (5, 'ЖКХ'), (6, 'Строительство, недвижимость, эксплуатация, проектирование'), (7, 'Услуги для бизнеса'), (8, 'Финансовый сектор'), (9, 'Электроника, приборостроение, бытовая техника, компьютеры и оргтехника'), (10, 'Энергетика')], verbose_name='Отрасль')),
                ('ITN', models.IntegerField(max_length=12, verbose_name='ИНН')),
                ('company_details', models.CharField(max_length=5000, verbose_name='Сведения о компании')),
                ('description', models.CharField(max_length=5000, verbose_name='Описание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=30, verbose_name='Должность')),
                ('conditions', models.CharField(max_length=500, verbose_name='Условия')),
                ('duties', models.CharField(max_length=500, verbose_name='Обязанности')),
                ('requirements', models.CharField(max_length=500, verbose_name='Требования')),
                ('published_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('company_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companyapp.companycard', verbose_name='Организация')),
            ],
        ),
    ]
