# Generated by Django 4.0.1 on 2022-01-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycard',
            name='ITN',
            field=models.IntegerField(verbose_name='ИНН'),
        ),
    ]
