# Generated by Django 4.0.1 on 2022-02-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, verbose_name='Отклик')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='Просмотрено')),
            ],
        ),
    ]
