# Generated by Django 4.0 on 2022-01-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.IntegerField(choices=[(1, 'Администратор'), (2, 'Работник'), (3, 'Компания')], default='1', verbose_name='Роль'),
        ),
    ]
