# Generated by Django 4.0.1 on 2022-02-17 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('messageapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workerapp', '0001_initial'),
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageToVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата отклика на вакансию')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='messageapp.message', verbose_name='Отклик')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workerapp.resume', verbose_name='Резюме')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('vacancy', models.ManyToManyField(to='companyapp.Vacancy', verbose_name='Вакансия')),
            ],
        ),
        migrations.CreateModel(
            name='LetterToCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True, verbose_name='Дата ответа')),
                ('text', models.TextField(blank=True, verbose_name='Письмо')),
                ('letter_to_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lkworkerapp.messagetovacancy', verbose_name='Ответ на отклик')),
            ],
        ),
    ]
